[package]
name = "wise_api"
version = "0.4.0"
edition = "2021"

[features]
simple_api = ["rcon/simple_api"]

[dependencies]
rcon = { path = "../rcon" }
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.128"
uuid = "1.10.0"
