[credentials]
address = "" # The address and port to connect to
password = "" # The password used to login

[polling]
wait_ms = 1000 # Milliseconds to wait between pollings
colldown_ms = 1000 # Milliseconds before opening another connection to the server

[exporting]
    
[exporting.websocket]
enabled = true # Enable or disable the websocket
address = "localhost:25052" # The address to which the websocket should bind to
access_token = "" # A unique token used by requesting applications to authenticate themselves (WIP: not currently implemented)
