[logging]
level = 0 # The logging level to use, overrides passed by argument. `-2` is only error, `2` is everything.

[rcon]
address = "" # The address and port to connect to
password = "" # The password used to login

[polling]
wait_ms = 1000 # Milliseconds to wait between pollings
cooldown_ms = 1000 # Milliseconds before opening another connection to the server

[exporting]
    
[exporting.websocket]
enabled = true # Enable or disable the websocket
address = "localhost:25052" # The address to which the websocket should bind to
# password = "" # A unique token used by requesting applications to authenticate themselves

tls = false # Enable or disable TLS
# cert_file = "" # Path to the certificate, only needs to be set if tls is enabled 
# key_file = "" # Path to the key file, only needs ot be set if tls is enabled
